# Generated by Django 6.1.1 on 2026-09-17 03:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBusae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('velocidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('manos_libres', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ultima_transmision', models.DateTimeField(null=True)),
                ('sincronizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sincronizado_en'],
            },
        ),
        migrations.CreateModel(
            name='DatosGenesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('hora_entrada', models.DateTimeField()),
                ('patio_ubicacion', models.CharField(blank=True, max_length=100)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('sincronizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ModuloDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('codigo_empleado', models.CharField(db_index=True, max_length=20, unique=True)),
                ('patio_asignado', models.CharField(blank=True, max_length=100)),
                ('cuota_diaria', models.IntegerField(default=20)),
                ('es_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EEMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True, unique=True)),
                ('fase_instalacion', models.CharField(blank=True, max_length=50)),
                ('fase_bocina', models.CharField(blank=True, max_length=50)),
                ('version_firmware', models.CharField(blank=True, max_length=50)),
                ('estado_fw', models.CharField(blank=True, max_length=50)),
                ('datos_dinamicos', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['datos_dinamicos'], name='buses_eemov_datos_d_d0a2de_gin')],
            },
        ),
        migrations.CreateModel(
            name='TareaExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('formato', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo_resultado', models.FileField(blank=True, upload_to='exports/')),
                ('error_mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampoConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField()),
                ('etiqueta', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('TEXTAREA', 'Área de Texto'), ('NUMBER', 'Número'), ('SELECT', 'Selección Única'), ('MULTISELECT', 'Selección Múltiple'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('FILE', 'Archivo')], max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('validaciones', models.JSONField(blank=True, default=dict)),
                ('requerido', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='buses.modulodinamico')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('modulo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='RegistroBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('patio', models.CharField(db_index=True, max_length=100)),
                ('tipo_mantenimiento', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('datos_dinamicos', models.JSONField(blank=True, default=dict)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['datos_dinamicos'], name='buses_regis_datos_d_fc87eb_gin')],
            },
        ),
    ]
