# Generated by Django 6.1.1 on 2026-09-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_atencion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('estado_gps', models.CharField(blank=True, max_length=50)),
                ('patio', models.CharField(db_index=True, max_length=100)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('hora_reporte', models.CharField(blank=True, max_length=20)),
                ('diagnostico', models.TextField(blank=True)),
                ('tecnico_nombre', models.CharField(max_length=150)),
                ('tecnico_codigo', models.CharField(db_index=True, max_length=50)),
                ('reporte_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-timestamp_atencion'],
            },
        ),
        migrations.CreateModel(
            name='ReportePendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('estado_gps', models.CharField(default='OFF', max_length=50)),
                ('patio', models.CharField(db_index=True, max_length=100)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('hora_reporte', models.CharField(blank=True, max_length=20)),
                ('diagnostico', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='eemovil',
            options={'ordering': ['bus_movil']},
        ),
        migrations.RemoveIndex(
            model_name='eemovil',
            name='buses_eemov_datos_d_d0a2de_gin',
        ),
        migrations.RemoveIndex(
            model_name='registrobitacora',
            name='buses_regis_datos_d_fc87eb_gin',
        ),
        migrations.AddField(
            model_name='eemovil',
            name='diagnostico',
            field=models.TextField(blank=True, default='Equipo en monitoreo preventivo'),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='estado',
            field=models.CharField(blank=True, default='OPERATIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='estado_bocina',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='estado_modem',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='hora',
            field=models.CharField(blank=True, default='08:00', max_length=20),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='patio',
            field=models.CharField(blank=True, default='Patio Curundu', max_length=100),
        ),
        migrations.AddField(
            model_name='eemovil',
            name='ultima_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='actualizacion_fw',
            field=models.CharField(blank=True, default='ACTUALIZADO', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='anillo',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='bocina',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='bocina_adecuacion',
            field=models.CharField(blank=True, default='ADECUADA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='bocina_carcasa',
            field=models.CharField(blank=True, default='INSTALADA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='bocina_regulador',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='boton_llamada',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='boton_panico',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='ctap',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='imei_busae',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='modem',
            field=models.CharField(blank=True, default='FUNCIONA', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='origen',
            field=models.CharField(default='reportes', max_length=30),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='respuesta_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='serie_ctap',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='serie_sim',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='sim_card',
            field=models.CharField(blank=True, default='ACTIVA', max_length=50),
        ),
        migrations.AlterField(
            model_name='campoconfiguracion',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('TEXTAREA', 'Área de Texto'), ('NUMBER', 'Número'), ('SELECT', 'Selección Única'), ('MULTISELECT', 'Selección Múltiple'), ('RADIO', 'Grupo Radio'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha'), ('FILE', 'Archivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eemovil',
            name='estado_fw',
            field=models.CharField(blank=True, default='ACTUALIZADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='eemovil',
            name='fase_bocina',
            field=models.CharField(blank=True, default='Adecuada', max_length=50),
        ),
        migrations.AlterField(
            model_name='eemovil',
            name='fase_instalacion',
            field=models.CharField(blank=True, default='Operativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='eemovil',
            name='version_firmware',
            field=models.CharField(blank=True, default='v2.4.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrobitacora',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='patio_asignado',
            field=models.CharField(blank=True, default='Patio Curundu', max_length=100),
        ),
    ]
