# Generated by Django 6.1.1 on 2026-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_historialatencion_reportependiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=100, unique=True)),
                ('valor', models.JSONField(default=dict)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('componente', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=100)),
                ('funcional', models.BooleanField(default=True)),
                ('danado', models.BooleanField(default=False)),
                ('tipo_dano', models.CharField(blank=True, max_length=100)),
                ('estado_accion', models.CharField(choices=[('Pendiente de revision', 'Pendiente de revisión'), ('Actualizado', 'Actualizado')], default='Pendiente de revision', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bus_movil', 'componente'],
            },
        ),
        migrations.CreateModel(
            name='InventarioFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True, unique=True)),
                ('placa', models.CharField(blank=True, db_index=True, max_length=20)),
                ('tipo_flota', models.CharField(default='Torino', max_length=50)),
                ('patio', models.CharField(blank=True, default='LOS PUEBLOS', max_length=100)),
                ('estado', models.CharField(default='OPERATIVO', max_length=50)),
                ('columnas_extra', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bus_movil'],
            },
        ),
    ]
