# Generated by Django 6.1.1 on 2026-09-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_gps_ok_post_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialatencion',
            name='datos_formulario',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historialatencion',
            name='tipo_mantenimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='adecuacion_electrica',
            field=models.CharField(blank=True, default='Adecuada', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='boton_puerta',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='ctap_anillo',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='ctap_estado',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='gps_estado',
            field=models.CharField(blank=True, default='Funcional', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='gps_vandalismo',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='radio_conexion',
            field=models.CharField(blank=True, default='Sí', max_length=10),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='radio_instalacion',
            field=models.CharField(blank=True, default='Sí', max_length=10),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='radio_pantalla',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='radio_parrilla',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='radio_pedal',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='simcard_estado',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioee',
            name='estado_accion',
            field=models.CharField(choices=[('Pendiente de revision', 'Pendiente de revisión'), ('Reparado', 'Reparado'), ('Reemplazado', 'Reemplazado'), ('Actualizado', 'Actualizado')], default='Pendiente de revision', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrobitacora',
            name='boton_llamada',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrobitacora',
            name='boton_panico',
            field=models.CharField(blank=True, default='Funcional', max_length=20),
        ),
    ]
