# Generated by Django 6.1.1 on 2026-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_historialatencion_datos_formulario_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datosbusae',
            index=models.Index(fields=['bus_movil', 'sincronizado_en'], name='idx_busae_bus_sync'),
        ),
        migrations.AddIndex(
            model_name='registrobitacora',
            index=models.Index(fields=['bus_movil', 'timestamp'], name='idx_bit_bus_time'),
        ),
        migrations.AddIndex(
            model_name='registrobitacora',
            index=models.Index(fields=['patio', 'timestamp'], name='idx_bit_patio_time'),
        ),
        migrations.AddIndex(
            model_name='registrobitacora',
            index=models.Index(fields=['tecnico', 'timestamp'], name='idx_bit_tec_time'),
        ),
        migrations.AddIndex(
            model_name='reportependiente',
            index=models.Index(fields=['patio', 'estado'], name='idx_rep_patio_estado'),
        ),
        migrations.AddIndex(
            model_name='reportependiente',
            index=models.Index(fields=['bus_movil', 'fecha_reporte'], name='idx_rep_bus_fecha'),
        ),
    ]
