# Generated by Django 6.1.1 on 2026-09-19 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_datosbusae_idx_busae_bus_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_codigo', models.CharField(blank=True, help_text='Código o username de respaldo', max_length=50)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('ATENDER', 'Atención de Falla'), ('LOGIN', 'Inicio de Sesión'), ('CONFIG', 'Cambio de Configuración')], db_index=True, max_length=20)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('registro_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['modelo', 'registro_id'], name='buses_audit_modelo_b87ce4_idx'), models.Index(fields=['accion', 'timestamp'], name='buses_audit_accion_4c1f93_idx'), models.Index(fields=['usuario', 'timestamp'], name='buses_audit_usuario_1f464d_idx')],
            },
        ),
    ]
