# Generated by Django 6.1.1 on 2026-09-19 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nombre', models.CharField(help_text='Tipo de equipo: Módem, CTAP, SIM Card, Sensor, etc.', max_length=100)),
                ('marca_modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, db_index=True, max_length=100)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=50)),
                ('bus_asignado', models.IntegerField(blank=True, db_index=True, help_text='Número de bus donde está instalado', null=True)),
                ('patio_ubicacion', models.CharField(default='CURUNDU', max_length=100)),
                ('estado', models.CharField(choices=[('INSTALADO', 'Instalado en Móvil'), ('EN_STOCK', 'En Stock / Almacén'), ('EN_TALLER', 'En Reparación / Taller'), ('DE_BAJA', 'Dado de Baja / Descartado')], db_index=True, default='EN_STOCK', max_length=30)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo_nombre', 'serie'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEstadoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('tipo_estado', models.CharField(choices=[('OPERATIVO', 'Operativo / Normal'), ('FALLA_CRITICA', 'Falla Crítica / Dañado'), ('ADECUACION_PENDIENTE', 'Adecuación / Por Instalar'), ('NO_APLICA', 'No Aplica / No Tiene')], default='OPERATIVO', max_length=30)),
                ('es_falla', models.BooleanField(default=False)),
                ('color', models.CharField(default='emerald', help_text='emerald, rose, amber, slate, cyan', max_length=30)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clave', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('TELEMETRIA_GPS', 'Telemetría & GPS'), ('AUDIO_ALERTAS', 'Audio & Alertas'), ('COMUNICACIONES_CTAP', 'Comunicaciones & CTAP'), ('SENSORES_BOTONES', 'Sensores & Botones'), ('ENERGIA_CABLEADO', 'Energía & Cableado'), ('OTROS', 'Otros Componentes')], default='TELEMETRIA_GPS', max_length=40)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_serie', models.BooleanField(default=False, help_text='Solicita ingresar serie al revisar')),
                ('requiere_imei', models.BooleanField(default=False, help_text='Solicita ingresar IMEI al revisar')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='reportependiente',
            name='prioridad',
            field=models.CharField(default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='reportependiente',
            name='sla_escalado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportependiente',
            name='sla_limite_horas',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='reportependiente',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialMovimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_anterior', models.IntegerField(blank=True, null=True)),
                ('bus_nuevo', models.IntegerField(blank=True, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('motivo', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='buses.activoee')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RevisionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.opcionestadocomponente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_componentes', to='buses.registrobitacora')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.tipocomponente')),
            ],
            options={
                'ordering': ['componente__orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='opcionestadocomponente',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='buses.tipocomponente'),
        ),
        migrations.AddField(
            model_name='activoee',
            name='tipo_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='buses.tipocomponente'),
        ),
        migrations.CreateModel(
            name='UnidadFueraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('motivo', models.CharField(choices=[('TALLER_MANTENIMIENTO', 'Taller de Mantenimiento Mecánico'), ('ACCIDENTE_SINIESTRO', 'Accidente / Siniestro'), ('BAJA_TEMPORAL', 'Baja Temporal / Espera de Repuestos'), ('PROCESO_LEGAL', 'Proceso Legal / Retenido'), ('OTRO', 'Otro Motivo')], default='TALLER_MANTENIMIENTO', max_length=50)),
                ('departamento_responsable', models.CharField(default='Taller de Mantenimiento', max_length=100)),
                ('fecha_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Fuera de Servicio (Activo)'), ('CERRADO', 'Reactivado / En Servicio')], db_index=True, default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_fuera_servicio_cerradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_fuera_servicio_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimientoEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_movil', models.IntegerField(db_index=True)),
                ('ciclo_dias', models.IntegerField(default=90, help_text='Periodicidad recomendada en días')),
                ('fecha_ultimo_mantenimiento', models.DateField()),
                ('fecha_proximo_vencimiento', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al Día'), ('PROXIMO', 'Próximo a Vencer (< 15 días)'), ('VENCIDO', 'Mantenimiento Vencido')], default='AL_DIA', max_length=20)),
                ('alertado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_preventivos', to='buses.tipocomponente')),
            ],
            options={
                'ordering': ['fecha_proximo_vencimiento'],
                'unique_together': {('bus_movil', 'componente')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='opcionestadocomponente',
            unique_together={('componente', 'valor')},
        ),
        migrations.AddIndex(
            model_name='activoee',
            index=models.Index(fields=['bus_asignado', 'tipo_nombre'], name='buses_activ_bus_asi_3dd8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='activoee',
            index=models.Index(fields=['estado', 'patio_ubicacion'], name='buses_activ_estado_524317_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadfueraservicio',
            index=models.Index(fields=['bus_movil', 'estado'], name='buses_unida_bus_mov_6c4f39_idx'),
        ),
    ]
