# Generated by Django 6.1.1 on 2026-09-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_activoee_opcionestadocomponente_tipocomponente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbusae',
            name='odometro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
