# Generated by Django 6.1.1 on 2026-09-23 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0010_alter_datosgenesis_hora_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioflota',
            options={'ordering': ['bus_movil'], 'verbose_name': 'Unidad de Flota', 'verbose_name_plural': 'Flota'},
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='dado_de_baja_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_dadas_de_baja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='estado_operativo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Fuera de servicio (Baja)'), ('MANTENIMIENTO', 'En mantenimiento')], db_index=True, default='ACTIVO', help_text='ACTIVO = genera reportes | BAJA = no genera reportes', max_length=20),
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='fecha_reactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='motivo_baja',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventarioflota',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
